name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0' # or your current Flutter version

    - name: Restore firebase_options.dart from secret
      run: |
        mkdir -p lib
        echo "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart

    - name: Install dependencies
      run: flutter pub get

    # - name: Analyze code
      # run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    # OPTIONAL: Deploy to Firebase App Distribution
    # Uncomment below if you want to deploy directly to Firebase

    # - name: Install Firebase CLI
    #   run: npm install -g firebase-tools

    # - name: Upload to Firebase App Distribution
    #   run: |
    #     firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
    #       --app <your-firebase-android-app-id> \
    #       --token ${{ secrets.FIREBASE_TOKEN }} \
    #       --groups testers
